### PR TITLE
Add AcDisplay to "Who else uses it?"

### PR DESCRIPTION
**Pull request by AChep**

### CODE REVIEW

**Comment by serso** [comment]
Hi, Have you had any difficulties in integrating Checkout library? Was is easy to integrate?

**Comment by tral** [comment]
In my humble opinion, you have to make an out-of-the-box working example for a simple app.
Like in this lib: https://github.com/anjlab/android-inapp-billing-v3
As a beginner in Java & Android, it was easy for me to integrate android-inapp-billing-v3, but I couldn't integrate yours, despite it's better of course...

**Comment by serso** [comment]
But there is a sample project in the app folder: https://github.com/serso/android-checkout/tree/master/app/src/main
You can use it as a template. Have you seen it? What difficulties did you have? I thought I wrote a thorough README but it might be not enough...

**Comment by tral** [comment]
Yeah, I've been trying opening your proj in Android Studio ("Open existing Android project") and encouraged some errors: http://i.imgur.com/xvMnSoJ.png

But the lib I mentioned before works  right out-of-the-box.
So, my advise to you - make the same sample.

**Comment by serso** [comment]
I opened an issue, please follow it: https://github.com/serso/android-checkout/issues/26

**Comment by AChep** [comment]
@serso it was easy to integrate, but I had to move the billing#connect() into the activity, because users were complaining about the increased RAM usage.

https://plus.google.com/108350206572240560236/posts/cR3VBfjoyn1

**Comment by serso** [comment]
Hm, that's intereseting. Do you call Billing#disconnect() in Activity#onDestroy() method?

**Comment by AChep** [comment]
@serso Thanks!

**Pull request merged**
